name: build-and-test

description: Shared action with basic setup for building and testing the package

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup node version with .nvmrc file
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      shell: bash

    - uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-v1-
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Build files
      run: yarn build
      shell: bash