name: Workflow that runs on pull requests

on:
  pull_request:

jobs:
  changesets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing dependencies and building packages
        uses: ./.github/actions/ci

      - name: Run tests
        uses: ./.github/actions/test
         